name: animexa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1
  hive: ^2.2.3
  awesome_notifications: ^0.10.0
  path_provider: ^2.1.5
  awesome_dialog: ^3.2.1
  firebase_app_check: ^0.3.1+3
  lottie: ^3.1.3 

  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  #cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.10
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.0
  url_launcher: ^6.0.0
  permission_handler: ^10.0.0
  fl_chart: 0.36.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

#    - images/default_profile.png
    - assets/
    - .env
    

    
flutter_native_splash:
  color: "#3369FF"
  image: assets/splashscreen.png
  android: true
  ios: true
